apiVersion: v1
kind: Service
metadata:
  name: object-detection-service
  labels: 
    app: object-detection
spec:
  selector:
    app: object-detection
  type: NodePort
  ports:
  - nodePort: 31000
    port: 5000
    targetPort: 5000
